# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: Kenneth Kebaara | Full-Stack Developer & Entrepreneur
# Edit next line, replacing 'techfolios' with your github username
url: "https://kebaara.com"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# SEO settings
description: "Kenneth Kebaara - Full-Stack Software Developer & Entrepreneur | 10+ years building React Native apps, SaaS platforms, and scalable web solutions. View portfolio, projects, and technical essays."
author: Kenneth Kebaara
keywords: "Kenneth Kebaara, Full-Stack Developer, Software Engineer, React Native Developer, SaaS Developer, Web Development, Mobile App Development, Ruby on Rails, Firebase, JavaScript, TypeScript, Entrepreneur, Denver Developer, USA2Kenya, WellVue, Fit By Jonetics, Portfolio, Technical Blog"

# Google Search Console verification (uncomment and add your verification code)
# google_search_console: "your-verification-code-here"

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
bio-page-label: Resume
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-3.html
theme-testimonials: theme-testimonials-builtin-1.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# Medium Integration
medium:
  username: kkebaara  # Update this with your actual Medium username
  enabled: true
  max_articles: 6

# Collections for better organization
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  essays:
    output: true
    permalink: /:collection/:name/

# Default front matter for collections
defaults:
  - scope:
      path: "projects"
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "essays"
      type: "essays"
    values:
      layout: "essay"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sitemap configuration
sitemap:
  exclude:
    - /css/
    - /js/
    - /_site/
    - /Gemfile*
    - /_config.yml
  include_articles: true
  collections:
    - projects
    - essays

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

